Resources updated
pydelhi/resources pull request #1
Opened 2019-01-20 20:09 UTC by realslimshanky

- Email templates updated
- README.md updated

2019-01-20 20:26 UTC, CuriousLearner requested changes
I'd rather prefer naming the folder `assets` or something else rather than `logo&images`

2019-01-20 20:27 UTC, CuriousLearner commented on templates/email_meetup_announcement.txt
> +## Call for Speakers
Please separate these out in different txt files.

2019-02-10 23:24 UTC, realslimshanky commented on templates/email_meetup_announcement.txt
> +## Call for Speakers
ACK

2019-02-10 23:27 UTC, realslimshanky commented
I've updated the PR as per request please review @CuriousLearner

2019-03-03 06:04 UTC, vipulgupta2048 reviewed
This would help a lot in the time to come. Thanks @realslimshanky 
Should we also include the template for venue partners that I wrote?

2019-03-03 06:04 UTC, vipulgupta2048 commented on templates/call_for_volunteers_organizations_dev_sprints.txt
> +
A link for explanation of what are Dev Sprints would be great. Since, many have the same doubt. We can use the PyCon India one, or write our own.

2019-03-03 06:10 UTC, realslimshanky commented on templates/call_for_volunteers_organizations_dev_sprints.txt
> +
Sure. Adding that to the template

2019-03-03 06:13 UTC, realslimshanky commented
@vipulgupta2048 can you please share the venue partner template here so that I can add it? or better yet make a new PR for that after this is merged?

2019-03-03 06:17 UTC, realslimshanky commented on templates/call_for_volunteers_organizations_dev_sprints.txt
> +
I've found this [blog](https://in.pycon.org/blog/2018/understanding-dev-sprints-2018.html) and it's more specific to PyCon India. Do you have some other blog in mind?

2019-03-03 18:36 UTC, vipulgupta2048 commented on templates/call_for_volunteers_organizations_dev_sprints.txt
> +
Yes, the very same.

2019-03-03 18:37 UTC, vipulgupta2048 commented
I will make a new PR, looking at it now. I think it would need some changes before being rendered out as a template.

2019-03-03 18:50 UTC, vipulgupta2048 commented
Also, for the logo. I think a transparent one would be better. I have one, but it's of low quality. 
![thumbnail](https://user-images.githubusercontent.com/22801822/53699944-56054f00-3e13-11e9-8e36-2195d7cbfdd1.png)

2019-04-14 03:21 UTC, kindavishal commented
Let me know if you'd need a transparent one, I can help out with that 🙂

2019-04-17 05:57 UTC, realslimshanky commented
@kindavishal thanks. can you please reach out to @rajataaron and help with the logo?

2019-04-17 12:54 UTC, kindavishal commented
> @kindavishal thanks. can you please reach out to @rajataaron and help with the logo?

Hi @rajataaron how can I help? Please let me know, you can find me on [Telegram](https://t.me/kindavishal)

2023-03-27 06:56 UTC, akshayaurora approved these changes

2023-03-27 06:57 UTC, akshayaurora commented
@realslimshanky do you have time to rebse?

2026-03-12 08:08 UTC, Daksh777 commented
I think we can close this PR since we've pretty much changed everything in terms of working and communications

2026-03-12 08:08 UTC, closed without merging